spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LRzN2EXCeQqreb2n7mZ_
            client-secret: 4T4e3bNyNh
            scope:
              - name
              - gender
              - birthday
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/after-login
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug


